[package]
name = "hurtbreak-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[features]
default = ["std_rng"]
std_rng = ["fastrand"]

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
fastrand = { version = "2.0", optional = true }
