[project]
name = "hurtbreak-trace"
version = "0.1.0"
description = "Provides a minimal API for hurtbreak's `.hurt` file format."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I", "UP", "B"]
mccabe.max-complexity = 10

[tool.ruff.lint.isort]
force-sort-within-sections = true
lines-between-types = 0
order-by-type = true
